// Generated by CoffeeScript 1.6.3
(function() {
  var loud, stdin, stdout, thru, trumpet, write;

  trumpet = require('trumpet')();

  thru = require('through');

  stdin = process.stdin, stdout = process.stdout;

  loud = trumpet.select('.loud').createStream();

  write = function(buffer) {
    return this.queue(buffer.toString().toUpperCase());
  };

  loud.pipe(thru(write)).pipe(loud);

  stdin.pipe(trumpet).pipe(stdout);

}).call(this);
