// Generated by CoffeeScript 1.6.3
(function() {
  var cipher, crypto, decrypt, password, tar, thru, untar, unzip, zlib;

  crypto = require('crypto');

  thru = require('through');

  zlib = require('zlib');

  tar = require('tar');

  cipher = process.argv[2];

  password = process.argv[3];

  decrypt = crypto.createDecipher(cipher, password);

  unzip = zlib.createGunzip();

  untar = tar.Parse();

  untar.on('entry', function(entry) {
    var hash, insert, path;
    if (!(entry.type === 'File')) {
      return;
    }
    hash = crypto.createHash('md5', {
      encoding: 'hex'
    });
    path = " " + entry.path + "\n";
    insert = thru(null, function() {
      return this.queue(path);
    });
    entry.pipe(hash).pipe(insert).pipe(process.stdout);
    return '';
  });

  process.stdin.pipe(decrypt).pipe(unzip).pipe(untar);

}).call(this);
