// Generated by CoffeeScript 1.6.3
(function() {
  var Spy;

  Spy = function(target, method) {
    var f, result;
    f = target[method];
    target[method] = function() {
      result.count += 1;
      return f.apply(target, arguments);
    };
    return result = {
      count: 0
    };
  };

  module.exports = Spy;

  /*
  spy = Spy(console, 'error')
  
  console.error 'hi!', 'hi?'  # first call
  console.error 'hi!', 'hi?'  # second call
  console.log spy.count       # 2
  console.error 'ok!', 'ok!'  # third call
  console.log spy.count       # 3
  */


}).call(this);
