// Generated by CoffeeScript 1.6.3
(function() {
  var fs;

  fs = require('fs');

  fs.readFile(process.argv[2], 'utf8', function(err, data) {
    return console.log(data.split('\n').length - 1);
  });

}).call(this);
