// Generated by CoffeeScript 1.6.3
(function() {
  var db;

  db = require('level')(process.argv[2]);

  db.get('levelmeup', function(e, d) {
    if (e) {
      throw e;
    }
    return console.log(d);
  });

}).call(this);
