// Generated by CoffeeScript 1.6.3
(function() {
  var deepEqual, eq, nums, slice;

  slice = Function.call.bind(Array.prototype.slice);

  module.exports = slice;

  deepEqual = require('assert').deepEqual;

  eq = deepEqual;

  nums = [1, 2, 3, 4, 5];

  eq(slice(nums, 0, 2), [1, 2]);

  eq(slice(nums, 1, 2), [2]);

}).call(this);
