// Generated by CoffeeScript 1.6.3
(function() {
  var filter, fs, matching, path, regex, _ref;

  fs = require('fs');

  _ref = process.argv.slice(2, 4), path = _ref[0], filter = _ref[1];

  regex = new RegExp('\\.' + filter);

  matching = function(d) {
    return regex.test(d);
  };

  fs.readdir(path, function(err, list) {
    var dir, _i, _len, _ref1, _results;
    _ref1 = list.sort();
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      dir = _ref1[_i];
      if (matching(dir)) {
        _results.push(console.log(dir));
      }
    }
    return _results;
  });

}).call(this);
