// Generated by CoffeeScript 1.6.3
(function() {
  var deps,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  deps = function(pkg, result) {
    var k, v;
    if (result == null) {
      result = [];
    }
    return ((function() {
      var _ref, _results;
      _ref = pkg.dependencies;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push([k, v]);
      }
      return _results;
    })()).reduce(function(prev, next) {
      var dep, k, v;
      k = next[0], v = next[1];
      dep = [k, v.version].join('@');
      if (!(__indexOf.call(prev, dep) >= 0)) {
        prev.push(dep);
      }
      return deps(v, prev).sort();
    }, result);
  };

  module.exports = deps;

}).call(this);
