// Generated by CoffeeScript 1.6.3
(function() {
  var connect, http, port, server, thru, upcase;

  http = require('http');

  thru = require('through');

  port = process.argv[2];

  upcase = function(buffer) {
    return this.queue(buffer.toString().toUpperCase());
  };

  connect = function(req, res) {
    if (req.method === 'POST') {
      return req.pipe(thru(upcase)).pipe(res);
    }
  };

  server = http.createServer(connect);

  server.listen(port);

}).call(this);
