// Generated by CoffeeScript 1.6.3
(function() {
  var connect, http, url;

  http = require('http');

  url = require('url');

  connect = function(req, res) {
    var date, parsed, result;
    parsed = url.parse(req.url, true);
    date = new Date(parsed.query.iso);
    result = '';
    if (/api\/parsetime/.test(parsed.pathname)) {
      result = {
        hour: date.getHours(),
        minute: date.getMinutes(),
        second: date.getSeconds()
      };
    } else if (/api\/unixtime/.test(parsed.pathname)) {
      result = {
        unixtime: date.getTime()
      };
    }
    res.writeHead(200, {
      'Content-Type': 'application/json'
    });
    return res.end(JSON.stringify(result));
  };

  http.createServer(connect).listen(8000);

}).call(this);
