// Generated by CoffeeScript 1.6.3
(function() {
  var duckCount, test,
    __slice = [].slice;

  duckCount = function() {
    var args, hasQuack;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    hasQuack = function(x) {
      return Object.prototype.hasOwnProperty.call(x, 'quack');
    };
    return args.filter(hasQuack).length;
  };

  module.exports = duckCount;

  test = function() {
    var birds, ok, turkey;
    ok = require('assert').ok;
    turkey = Object.create({
      quack: true
    });
    birds = [
      turkey, {
        quack: true
      }, {
        quack: true
      }, {
        quack: true
      }
    ];
    return ok(duckCount.apply(null, birds) === 3);
  };

  test();

}).call(this);
