// Generated by CoffeeScript 1.6.3
(function() {
  var log;

  log = function(buff) {
    var i, ui8, _i, _ref;
    ui8 = new Uint8Array(buff.length);
    for (i = _i = 0, _ref = buff.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      ui8[i] = buff[i];
    }
    console.log(JSON.stringify(ui8));
    return '';
  };

  process.stdin.on('data', log);

}).call(this);
