// Generated by CoffeeScript 1.6.3
(function() {
  var feed, net, strftime;

  net = require('net');

  strftime = require('strftime');

  feed = function(socket) {
    return socket.end(strftime('%Y-%m-%d %H:%M'));
  };

  net.createServer(feed).listen(8000);

}).call(this);
