// Generated by CoffeeScript 1.6.3
(function() {
  var post, stdin, stdout;

  post = require('request').post;

  stdin = process.stdin, stdout = process.stdout;

  stdin.pipe(post('http://localhost:8000')).pipe(stdout);

}).call(this);
