// Generated by CoffeeScript 1.6.3
(function() {
  var connect, file, http, map, upcase;

  http = require('http');

  map = require('through2-map');

  file = process.argv[2];

  upcase = function(chunk) {
    return chunk.toString().toUpperCase();
  };

  connect = function(req, res) {
    if (req.method === 'POST') {
      return req.pipe(map(upcase)).pipe(res);
    }
  };

  http.createServer(connect).listen(8000);

}).call(this);
