// Generated by CoffeeScript 1.6.3
(function() {
  var db, k, v, _ref;

  db = require('level')(process.argv[2]);

  _ref = JSON.parse(process.argv[3]);
  for (k in _ref) {
    v = _ref[k];
    db.put(k, v);
  }

}).call(this);
