// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(arr, iter) {
    var x, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      x = arr[_i];
      _results.push(iter(x));
    }
    return _results;
  };

}).call(this);
