// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(f, n) {
    var i, _i;
    for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
      f();
    }
    return '';
  };

}).call(this);
