// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(messages) {
    var isShort;
    isShort = function(x) {
      return x.message.length < 50;
    };
    return messages.filter(isShort).map(function(x) {
      return x.message;
    });
  };

}).call(this);
