// Generated by CoffeeScript 1.6.3
(function() {
  var isShort;

  isShort = function(x) {
    return x.message.length < 50;
  };

  module.exports = function(messages) {
    return messages.filter(isShort).map(function(x) {
      return x.message;
    });
  };

}).call(this);
