// Generated by CoffeeScript 1.6.3
(function() {
  var crypto, decrypt, passphrase;

  crypto = require('crypto');

  passphrase = process.argv[2];

  decrypt = crypto.createDecipher('aes256', passphrase);

  process.stdin.pipe(decrypt).pipe(process.stdout);

}).call(this);
