// Generated by CoffeeScript 1.6.3
(function() {
  var connect, file, fs, http;

  http = require('http');

  fs = require('fs');

  file = process.argv[2];

  connect = function(req, res) {
    return fs.createReadStream(file).pipe(res);
  };

  http.createServer(connect).listen(8000);

}).call(this);
