// Generated by CoffeeScript 1.6.3
(function() {
  var db;

  db = require('level')(process.argv[2]);

  db.createReadStream().on('data', function(d) {
    return console.log("" + d.key + "=" + d.value);
  }).on('error', function(e) {
    if (e) {
      return console.error(e);
    }
  });

}).call(this);
