// Generated by CoffeeScript 1.6.3
(function() {
  var i, split, thru, transform;

  split = require('split');

  thru = require('through');

  i = 0;

  transform = function(line) {
    i += 1;
    if (i % 2) {
      return this.queue(line.toString().toLowerCase() + "\n");
    } else {
      return this.queue(line.toString().toUpperCase() + "\n");
    }
  };

  process.stdin.pipe(split()).pipe(thru(transform)).pipe(process.stdout);

}).call(this);
