// Generated by CoffeeScript 1.6.3
(function() {
  var done, http, url;

  http = require('http');

  url = process.argv[2];

  done = function(res) {
    res.setEncoding('utf8');
    res.on('error', console.error);
    return res.on('data', console.log);
  };

  http.get(url, done).on('error', console.error);

}).call(this);
