// Generated by CoffeeScript 1.6.3
(function() {
  var con, db, done, multilevel, net;

  net = require('net');

  multilevel = require('multilevel');

  db = multilevel.client();

  con = net.connect(4545);

  con.pipe(db.createRpcStream()).pipe(con);

  done = function(err, value) {
    if (err) {
      throw err;
    }
    console.log(value);
    return con.end();
  };

  db.get('multilevelmeup', done);

}).call(this);
