// Generated by CoffeeScript 1.6.3
(function() {
  var db, level, sublevel;

  level = require('level');

  sublevel = require('level-sublevel');

  db = sublevel(level(process.argv[2]));

  db.sublevel('robots').put('slogan', 'beep boop');

  db.sublevel('dinosaurs').put('slogan', 'rawr');

}).call(this);
