// Generated by CoffeeScript 1.6.3
(function() {
  var filter, match, path, _ref;

  match = require('filter');

  _ref = process.argv.slice(2, 4), path = _ref[0], filter = _ref[1];

  match(path, filter, function(err, list) {
    var dir, _i, _len, _results;
    if (err) {
      return console.error(err);
    } else {
      _results = [];
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        dir = list[_i];
        _results.push(console.log(dir));
      }
      return _results;
    }
  });

}).call(this);
