// Generated by CoffeeScript 1.6.3
(function() {
  var byKey, data, db, parsePush, range;

  db = require('level')(process.argv[2]);

  range = {
    start: 'gibberish',
    end: 'gibberish\xff'
  };

  data = [];

  byKey = function(a, b) {
    return a.key > b.key;
  };

  parsePush = function(d) {
    var result;
    result = {
      key: parseInt(d.key.replace('gibberish', '')),
      value: "" + d.key + "=" + d.value
    };
    return data.push(result);
  };

  db.createReadStream(range).on('error', function(err) {
    if (err.notFound) {
      return console.log(err);
    } else {
      throw err;
    }
  }).on('data', parsePush).on('close', function() {
    var d, _i, _len, _ref, _results;
    _ref = data.sort(byKey);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      d = _ref[_i];
      _results.push(console.log(d.value));
    }
    return _results;
  });

}).call(this);
