// Generated by CoffeeScript 1.6.3
(function() {
  var db, get, i, _i;

  db = require('level')(process.argv[2]);

  get = function(key) {
    return db.get(key, (function(key) {
      return function(err, data) {
        if (err) {
          if (!err.notFound) {
            throw err;
          }
        } else {
          return console.log("" + key + "=" + data);
        }
      };
    })(key));
  };

  for (i = _i = 0; _i <= 100; i = ++_i) {
    get('gibberish' + i);
  }

}).call(this);
