// Generated by CoffeeScript 1.6.3
(function() {
  var concat, transform;

  concat = require('concat-stream');

  transform = function(data) {
    return console.log(data.toString().split('').reverse().join(''));
  };

  process.stdin.pipe(concat(transform));

}).call(this);
