// Generated by CoffeeScript 1.6.3
(function() {
  var logger,
    __slice = [].slice;

  logger = function(prefix) {
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.log.apply(null, [prefix].concat(args));
    };
  };

  module.exports = logger;

}).call(this);
