// Generated by CoffeeScript 1.6.3
(function() {
  var reduce, test;

  reduce = function(arr, reducer, init) {
    var recur;
    recur = function(i, prev) {
      var reduced;
      if (i >= arr.length) {
        return prev;
      }
      reduced = reducer(prev, arr[i], i, arr);
      return recur(i + 1, reduced);
    };
    return recur(0, init);
  };

  module.exports = reduce;

  test = function() {
    var init, ok, result, sum;
    ok = require('assert').ok;
    sum = function(prev, curr, i, arr) {
      return prev + curr;
    };
    result = reduce([1, 2, 3], sum, init = 0);
    return ok(result === 6);
  };

}).call(this);
