// Generated by CoffeeScript 1.6.3
(function() {
  var rewrite;

  rewrite = function(buff) {
    var i, _i, _ref;
    for (i = _i = 0, _ref = buff.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (buff[i] === 46) {
        buff.write('!', i);
      }
    }
    return console.log(buff);
  };

  process.stdin.on('data', rewrite);

}).call(this);
