// Generated by CoffeeScript 1.6.3
(function() {
  var fs, log, newline;

  fs = require('fs');

  newline = new Buffer('\n')[0];

  log = function(err, buff) {
    var i, offset, _i, _ref;
    offset = 0;
    for (i = _i = 0, _ref = buff.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (buff[i] === newline) {
        console.log(buff.slice(offset, i));
        offset = i + 1;
      }
    }
    console.log(buff.slice(offset));
    return '';
  };

  fs.readFile(process.argv[2], log);

}).call(this);
