// Generated by CoffeeScript 1.6.3
(function() {
  var fs, log, newline, path;

  fs = require('fs');

  path = process.argv[2];

  newline = new Buffer('\n')[0];

  log = function(err, data) {
    var line, _i, _len, _ref, _results;
    _ref = data.toString().split('\n');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      _results.push(console.log(new Buffer(line)));
    }
    return _results;
  };

  fs.readFile(path, log);

}).call(this);
